### PR TITLE
Add support to specify host and port

### PR DESCRIPTION
**Pull request by oliverhr**
I use this to add support for port and host specification without changing the signature for the constructor.

### CODE REVIEW

**Comment by oliverhr** [comment]
Test fail because a lib specified on package.json

> Error: version not found: babel-core@5.6.17

**Comment by jmdobry** [comment]
Did you modify the file in `dist` directly? Just modify `src/index.js`, and when I make the release, I'll run the build and `dist/js-data-redis.js` will be generated. When you modified `src/index.js`, you forgot to add the `host` and `port` arguments to `redis.createClient`.

**Comment by oliverhr** [comment]
Ok let me cancel the PR and make it again.

**Comment by oliverhr** [comment]
oh I see the error the I didn't touch the dist/ but yes I do some undos without check again src/, sorry.

**Pull request closed without merging**
